<?php

namespace UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChapterStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapterStateRepository extends EntityRepository
{
}
