<?php

namespace KernelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPositionRepository extends EntityRepository
{
}
