<?php

namespace DemoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DemoEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemoEntityRepository extends EntityRepository
{
}
