<?php

namespace demoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * demoEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demoEntityRepository extends EntityRepository
{
}
