<?php

namespace UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcmRepository extends EntityRepository
{
}
