<?php

namespace UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTestRepository extends EntityRepository
{
}
